-- Databricks notebook source
-- MAGIC %md
-- MAGIC ###Overview
-- MAGIC This notebooks contains complete SPARK SQL / DELTA LAKE SQL  Tutorial
-- MAGIC ###Details
-- MAGIC | Detail Tag | Information
-- MAGIC | - | - |
-- MAGIC | NOTEBOOK | SQL High level Commands List  
-- MAGIC | Originally Created By | Raveendra  
-- MAGIC | Reference And Credits  | apache.spark.org  & databricks.com
-- MAGIC
-- MAGIC ###History
-- MAGIC |Date | Developed By | comments
-- MAGIC |----|-----|----
-- MAGIC |23/05/2021|Ravendra| Initial Version
-- MAGIC | Find more Videos | Youtube   | <a href="https://www.youtube.com/watch?v=FpxkiGPFyfM&list=PL50mYnndduIHRXI2G0yibvhd3Ck5lRuMn" target="_blank"> Youtube link </a>|

-- COMMAND ----------

-- MAGIC %md
-- MAGIC
-- MAGIC # SQL COMMANDS 
-- MAGIC
-- MAGIC
-- MAGIC |DDL | DML | DRL |DCL | TCL
-- MAGIC |----|-----|----|----|----
-- MAGIC | CREATE | INSERT | SELECT | GRANT | COMMIT
-- MAGIC | DROP | DELETE | SELECT | REVOKE | ROLLBACK
-- MAGIC | ALTER | UPDATE | SELECT | -- | SAVEPOINT
-- MAGIC | RENAME | MERGE | -- | -- | --
-- MAGIC | TRUNCATE | -- | --| --|--
-- MAGIC
